# Site settings
title: Syed Fuad
email: smf0100@auburn.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a postdoctoral fellow at Auburn University. 
  My research agenda is broadly focused on developing models of resource use behavior in agricultural and geosptial economics. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://syedmfuad.net" # the base hostname & protocol for your site
googlescholar_username: user=COaq5fAAAAAJ&hl=en
orcid: https://orcid.org/0000-0002-2462-0269
github_username:  syedmfuad
linkedin_username: syedmfuad
# twitter_username: 
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
